CREATE TABLE purchaser (purchaser_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(25) NOT NULL UNIQUE, created_date TIMESTAMP NOT NULL, password VARCHAR(30) NOT NULL, role VARCHAR(10) NOT NULL, salt VARCHAR(30) NOT NULL);
CREATE TABLE product (product_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(25) NOT NULL UNIQUE, created_date TIMESTAMP NOT NULL);
CREATE TABLE purchase_product (
purchaseProd_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
purchaser_id INT NOT NULL,
product_id INT NOT NULL,
NAME VARCHAR(25) NOT NULL,
sales_date TIMESTAMP NOT NULL,
FOREIGN KEY (purchaser_id) REFERENCES purchaser(purchaser_id),
FOREIGN KEY (product_id) REFERENCES product(product_id));